#!/bin/bash

GOARCH=$(go env GOARCH)
GOOS=$(go env GOOS)

SCHEME="https"
HOST="server.rsmaxwell.co.uk"
PORT=""
BASE="/archiva/repository"
URL="${SCHEME}://${HOST}${PORT}/${BASE}"

REPOSITORY="build"
GROUPID="com.rsmaxwell.players"
NAME="players-api"
ARTIFACTID=${NAME}-${GOARCH}-${GOOS}
ENDPOINT=${URL}/${REPOSITORY}/${GROUPID//.//}/${ARTIFACTID}/maven-metadata.xml
METADATA=$(./build/maven-metadata.xml)

rm -rf ${METADATA}

wget --quiet --output-document=${METADATA} ${ENDPOINT}
result=$?
if [ ! ${result} -eq 0 ]; then
    echo "Error: $0[${LINENO}]"
    echo "Could not get 'maven-metadata.xml'"
    exit 1
fi

line=$(grep "<version>" ${METADATA})
if [ ${#line} == 0 ]; then
    echo "Error: $0[${LINENO}]"
    echo "Could parse version"
    exit 1
fi

regex="<version>(.*)</version>"
if [[ ! ${line} =~ ${regex} ]]; then
    echo "Error: $0[${LINENO}]"
    echo "Could parse version"
    exit 1
fi

players_api_version="${BASH_REMATCH[1]}"
echo "players_api_version: ${players_api_version}"

cat >>version <<EOF
export players_api_version=${players_api_version}
EOF
