#!/bin/bash

set -x
rc=0

pwd 
ls -al 
tree

generate_test_data=$(find $(pwd)build -name generate-test-data*)
players_api=$(find $(pwd)/build -name players-api*)
testclient=$(find $(pwd) -name testclient)

cd build
jq . version.json

export PORT=4201
export PLAYERS_API_ROOTDIR="database"

${generate_test_data}
${players_api} &
PID=$!

${testclient}
result=$?
if [ ! ${result} -eq 0 ]; then
    echo "Error: $0[${LINENO}]"
    rc=1
fi

echo "killing the 'players-api' process"
kill ${PID}

exit ${rc}
