#!/bin/bash

#**************************************************************
# Get the version
#**************************************************************
cd build
pwd
ls -al 
jq . version.json

generate_test_data=$(find . -name generate-test-data*)
players_api=$(find . -name players-api*)

export PORT=4201
export PLAYERS_API_ROOTDIR="database"

${generate_test_data}
${players_api} &
PID=$!

../testclient

echo "killing the 'players-api' process"
kill ${PID}
